### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by EAZY56666** [CheatBreakerNet/Client#50] opened 2023-07-28 23:55 UTC
### Describe the bug

Hello, I have a problem when starting the launcher, when I click launch 1.8.9 it starts to load everything but when I get to "settings" it freezes and does not advance and the program stops responding, could you help me, thanks

### Steps To Reproduce

1. open launcher
2. click "launch 1.8.9"

### Expected Behavior

start correctly

### Environment

```markdown
OS: W10
Game version: 1.8.9
Game build number: 
Launcher version: 2.3.6
JRE version: 8u51
```

**Comment by ShonP40** [comment] 2023-07-29 00:05
1. Your problem isn't related to the launcher
2. Try the following steps:
   - Change your DNS servers to CloudFlare's ones (`1.1.1.1` & `1.0.0.1`)
   - Flush your DNS cache using the following command in `CMD`: `ipconfig /flushdns`
   - Install all available Windows updates
   - Restart your PC and try to launch the game again
   - If none of those steps worked for you, try a VPN
3. If none of the steps above worked for you, simply wait 6-24 hours for the SSL cache to clear

**Comment by ShonP40** [comment] 2023-07-29 17:51
@EAZY56666 Try the steps on our [Self Diagnostics](https://cheatbreaker.net/self-diagnostics) page in the `Client hanging on loading settings` section

Should fix your issue

**Comment by EAZY56666** [comment] 2023-07-30 18:39
> 1. Your problem isn't related to the launcher
> 2. Try the following steps:
>    
>    * Change your DNS servers to CloudFlare's ones (`1.1.1.1` & `1.0.0.1`)
>    * Flush your DNS cache using the following command in `CMD`: `ipconfig /flushdns`
>    * Install all available Windows updates
>    * Restart your PC and try to launch the game again
>    * If none of those steps worked for you, try a VPN
> 3. If none of the steps above worked for you, simply wait 6-24 hours for the SSL cache to clear

No other client fails me, the only one is the cheatbreaker, it's not a problem with my pc. tysm

**Comment by Tellinq** [comment] 2023-07-30 19:00
> it's not a problem with my pc. tysm
You don't really know that. Are you on a modified version of Windows? This includes but is not limited to:
- "Optimization"/"Tweaking" scripts
- Custom ISOs
- Playbooks

If any of these meets your criteria on what I'm asking, please say what you are using.

**Comment by ShonP40** [comment] 2023-07-30 19:01
Other clients working for you doesn’t mean that the issue is with the client.
We simply got a newer SSL root certificate that causes issues with older OS installs.

As stated above, go over the steps on our [Self Diagnostics](https://cheatbreaker.net/self-diagnostics) page in the `Client hanging on loading settings` section to fix the issue.

If you don’t want to do that, simply close the issue.

**Comment by EAZY56666** [comment] 2023-08-01 00:46
It doesn't work, I'll close this, thanks for your time

**Closed** 2023-08-01 00:46 UTC
Labels: bug

**Comment by ShonP40** [comment] 2023-08-01 02:50
Works fine for everyone who tried, which means that you didn’t, but sure up to you.
